### PR TITLE
Proposal of Personalized LLM Agent based on KubeEdge-Ianvs Cloud-Edge…

### PR DESCRIPTION
**Pull request by Frank-lilinjie**
… Collaborative Lifelong Learning

### CODE REVIEW

**Review by MooreZheng — CHANGES_REQUESTED** [review]
The overall format looks great. 

This proposal might need to focus on personalized LLM agent Scheme with different personalized models, including project title, dataset, and architecture. The personalized LLM agent needs to cooperate with lifelong modules to ensure it is extendable in the future.

**Comment by MooreZheng** [comment]
@hsj576 might also need to take a look at this proposal

**Comment by hsj576** [comment]
The overall content looks fine to me.
However, the implementation details of lifelong learning are not mentioned in the proposal, and the scheme of single task learning is adopted in the figure of 3.3 Ianvs Implement.

**Comment by MooreZheng** [comment]
Related issue and PR: https://github.com/kubeedge/ianvs/issues/99 https://github.com/kubeedge/ianvs/pull/128 https://github.com/kubeedge/ianvs/pull/138 https://github.com/kubeedge/ianvs/pull/154

**Pull request closed without merging**
