### PR TITLE
Proposal for Multimodal Large Model Joint Learning Algorithm: Reproduction Based on KubeEdge-Ianvs

### LINKED ISSUE #123: Multimodal Large Model Joint Learning Algorithm: Reproduction Based on KubeEdge-Ianvs
**What would you like to be added/modified**:
A benchmark suite for multimodal large language models deployed at the edge using KubeEdge-Ianvs:
1. Modify and adapt the existing edge-cloud data collection interface to meet the requirements of multimodal data collection;
2. Implement a Multimodal Large Language Model (MLLM) benchmark suite based on Ianvs;
3. Reproduce mainstream multimodal joint learning (training and inference) algorithms and integrate them into Ianvs single-task learning;
4. (_Advanced_) Test the effectiveness of multimodal joint learning in at least one of Ianvs' advanced paradigms (lifelong learning, incremental learning, federated learning, etc.).

**Why is this needed**:
KubeEdge-Ianvs currently focuses on edge-cloud collaborative learning (training and inference) for a single modality of data. However, edge devices, such as those in autonomous vehicles, often capture multimodal data, including GPS, LIDAR, and Camera data. Single-modal learning can no longer meet the precise inference requirements of edge devices. Therefore, this project aims to integrate mainstream multimodal large model joint learning algorithms into KubeEdge-Ianvs edge-cloud collaborative learning, providing multimodal learning capabilities.

**Recommended Skills**:
TensorFlow/Pytorch, LLMs, KubeEdge-Ianvs

**Useful links**:
[KubeEdge-Ianvs](https://github.com/kubeedge/ianvs)
[KubeEdge-Ianvs Benchmark Test Cases](https://github.com/kubeedge/ianvs/blob/main/examples/robot-cityscapes-synthia/lifelong_learning_bench/semantic-segmentation/README.md)
[Building Edge-Cloud Synergy Simulation Environment with KubeEdge-Ianvs](https://github.com/kubeedge/ianvs/blob/main/docs/guides/how-to-build-simulation-env.md)
[Artificial Intelligence - Pretrained Models Part 2: Evaluation Metrics and Methods](https://std.samr.gov.cn/gb/search/gbDetailed?id=0DF2C51A80293207E06397BE0A0AF1DA)
[Example LLMs Benchmark List](https://github.com/terryyz/llm-benchmark)
[awesome-multimodal-ml](https://github.com/pliang279/awesome-multimodal-ml)
[Awesome-Multimodal-Large-Language-Models](https://github.com/BradyFU/Awesome-Multimodal-Large-Language-Models)

### PR DESCRIPTION
**Pull request by aryan0931**
**What type of PR is this?**
/kind feature

**What this PR does / why we need it**:
Proposal for [Multimodal Large Model Joint Learning Algorithm: Reproduction Based on KubeEdge-Ianvs](https://github.com/kubeedge/ianvs/issues/123)

**Which issue(s) this PR fixes**:
Fixes #123

### CODE REVIEW

**Review by MooreZheng — COMMENTED** [review]
This proposal is developed after the discussion on https://github.com/kubeedge/ianvs/pull/163.  Considering the limited time of LFX, it is suggested to build based on the existing dataset and datatype.

**Review by MooreZheng — CHANGES_REQUESTED** [review]
1. There are a few comments to discuss what would be expected in this proposal. 
Ref: https://github.com/kubeedge/ianvs/pull/167#pullrequestreview-2467663312

2. This pull request contains 4 commits with vague commit messages (like "updated"), which might make maintenance difficult, especially considering the number of contributors, pull requests, and their commits in KubeEdge Ianvs recently. After all the comments are tackled, in the final stage, @aryan0931 can squash the commits into one using [rebase techniques](https://blog.kinboy.wang/2019/04/09/Git-%E5%8E%8B%E7%BC%A9%E5%A4%9A%E4%B8%AAcommit%E4%B8%BA%E5%8D%95%E4%B8%AAcommit/). Besides, a suggested commit message would be "add proposal of xxx"

**Review by MooreZheng — COMMENTED** [review]
This version looks good to me. It proposes to add MLM in the ianvs/example/Cloud_Robotics. The timely works and revisions from @aryan0931 is appreciated. Looking forward to see future implementations~

**Comment by MooreZheng** [comment]
We need another lgtm to go. @hsj576 might want to take a look at the proposal.

**Review by hsj576 — APPROVED** [review]
/lgtm

**Review by MooreZheng — APPROVED** [review]
All reviewer comments are tackled. Good job!

**Pull request merged**
