### PR TITLE
fix slack url

### PR DESCRIPTION
**Pull request by wbc6080**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
Update slack invitation link to CNCF, ref: https://github.com/kubeedge/community/issues/185
**Which issue(s) this PR fixes**:

Fixes #

### CODE REVIEW

**Review by Shelley-BaoYue — COMMENTED** [review]
Please rebase new main branch

**Comment by wbc6080** [comment]
> Please rebase new main branch
Done

**Pull request merged**
