### PR TITLE
add: Heterogeneous Multi-Edge Collaborative Neural Network Inference for High Mobility Scenarios: Base on KubeEdge-Ianvs proposal

### PR DESCRIPTION
**Pull request by wyoung1**
Heterogeneous Multi-Edge Collaborative Neural Network Inference for High Mobility Scenarios: Base on KubeEdge-Ianvs proposal

What type of PR is this?
/kind design

What this PR does / why we need it:
The PR is a proposal to Enhance the capabilities of existing multi-edge inference paradigm by providing automatic partitioning and scheduling functions, and create a new benchmarking job tailored for high-mobility scenarios.
Which issue(s) this PR fixes:
https://github.com/kubeedge/ianvs/issues/100

Fixes #

### CODE REVIEW

**Review by MooreZheng — CHANGES_REQUESTED** [review]
There is a CI issue that remain to be resolved, see https://github.com/kubeedge/ianvs/actions/runs/11074555058/job/31478061043?pr=153

**Review by MooreZheng — COMMENTED** [review]
For your information, this proposal heads to [this issue](https://github.com/kubeedge/ianvs/issues/100) and has tackled previous comments in https://github.com/kubeedge/ianvs/pull/115 , which looks good to me.

**Review by hsj576 — APPROVED** [review]
/lgtm

**Review by MooreZheng — APPROVED** [review]
It's great to see the proposal from @wyoung1 , and the proposal is appreciated with reviewer comments tackled.

**Comment by MooreZheng** [comment]
Related issue and PR: https://github.com/kubeedge/ianvs/issues/100 https://github.com/kubeedge/ianvs/pull/115 https://github.com/kubeedge/ianvs/pull/153 https://github.com/kubeedge/ianvs/pull/148 https://github.com/kubeedge/ianvs/pull/151

**Pull request merged**
