### PR TITLE
Updated docs, and few other files.

### PR DESCRIPTION
**Pull request by Sai-Suraj-27**
**Documentation Update**

**Updated a few docs by correcting different spelling and grammatical mistakes, also updated the CNCF Code of Conduct link in Contributing.md file that was previously broken (showing error 404 page not found).**:

**This PR fixes mistakes in the docs, and makes it clean and better**:

### CODE REVIEW

**Comment by Sai-Suraj-27** [comment]
Hi, I tried to correct most of the spelling and grammatical mistakes in the docs, I tried my best to make the docs look better, this is my first contribution to **Ianvs**, and I hope you like it. Thank you.

**Comment by Sai-Suraj-27** [comment]
Hi, @luosiqi @MooreZheng It's been a long time since I made this PR, I have just corrected simple mistakes in many docs to make them look better. So, you can look into the changes once and merge the PR. It's pretty good as I tried to cover many docs and correct as many mistakes as possible. Thank you.

**Comment by MooreZheng** [comment]
> Hi, @luosiqi @MooreZheng It's been a long time since I made this PR, I have just corrected simple mistakes in many docs to make them look better. So, you can look into the changes once and merge the PR. It's pretty good as I tried to cover many docs and correct as many mistakes as possible. Thank you.

Hi @Sai-Suraj-27 good to learn about the pr and sorry for the late reply due to my recent busy schedule. Welcome to KubeEdge and glad to see further contributions. :D

**Pull request merged**
