### PR TITLE
add unknown task process

### PR DESCRIPTION
**Pull request by xiaomoguhzz**
**What type of PR is this?**
add new feature

**What this PR does / why we need it**:
This pull request adds two unknown process handling algorithms and publishes a benchmark on the open-source dataset 'yaoba', which will attract more developers to join and expand the 'ianvs' community.
**Which issue(s) this PR fixes**:

None
Fixes #

### CODE REVIEW

**Review by MooreZheng — CHANGES_REQUESTED** [review]
Hi @xiaomoguhzz Welcome to KubeEdge SIG AI! Thank you and good to see the pull request. 

Here are also two suggestions for your consideration. 
1. Following the community instruction, such a large pull request typically requires a proposal detailedly describing what this pull request aims to do. 
2. Unknown task processing is a key component in lifelong learning. The pull request should work in ianvs - Lifelong Learning, instead of ianvs - SingleTaskLearning.

**Comment by MooreZheng** [comment]
> Thank you and good to see the pull request. Here are two comments before merging it.
> 
> 1. Following the community instruction, such a large pull request typically requires a proposal detailedly describing what this pull request aims to do.
> 2. Unknown task processing, in fact, is a key component in lifelong learning. The pull request should work in ianvs - Lifelong Learning, instead of ianvs - SingleTaskLearning.

For the first comment, an proposal example may be helpful for you  
- Proposal doc: https://github.com/kubeedge/ianvs/blob/main/docs/proposals/algorithms/lifelong-learning/Unknown_Task_Recognition_Algorithm_Reproduction_based_on_Lifelong_Learning_of_Ianvs.md
- Proposal Pull request: https://github.com/kubeedge/ianvs/pull/41

**Comment by SunayKulkarni** [comment]
## Review of PR #71 — add unknown task process

**Recommendation:** This PR was merged but contains several unresolved issues 
that prevent the yaoba example from running. The following problems were 
identified by inspecting the merged code:

**Bug 1 — Hardcoded absolute dataset path**
In `singletask_learning_boost/testenv/testenv.yaml`:
```yaml
image_folder_url: "/home/wjj/wjj/Public/code/ianvs/dataset/yaoba/images"
```
This path only exists on the original author's machine. Every other user 
gets a `FileNotFoundError` at dataset loading.

**Bug 2 — requirements.txt in wrong directory**
`requirements.txt` was placed at `singletask_learning_boost/readme/requirements.txt` 
instead of `singletask_learning_boost/requirements.txt`. Running 
`pip install -r requirements.txt` from the example root fails with 
`FileNotFoundError`.

**Bug 3 — Outdated dependency pins that no longer install**
`mmcv-full==1.7.1` no longer exists on PyPI under that name (renamed to `mmcv` 
in mmcv v2.0.0). `torch==1.13.0` is incompatible with Python 3.11+ and 
modern CUDA drivers. These pins make the example uninstallable on any modern 
system.

**Bug 4 — Custom paradigm `singletasklearning_acboost` not in Ianvs core**
The paradigm type declared in `algorithm.yaml` is not registered in 
`core/testcasecontroller/algorithm/paradigm/`. This will cause a 
`ClassNotFoundError` at runtime unless there is undocumented registration 
code elsewhere.

**Bug 5 — GPU hardcoded with no CPU fallback**
Both `basemodel.py` files contain `cfg.gpu_ids = [0]` with no 
`torch.cuda.is_available()` check. Crashes on CPU-only machines and CI servers.

**Reproduce attempt:**
Attempted to set up environment on Fedora Linux, Python 3.11:
$ pip install -r examples/yaoba/singletask_learning_boost/readme/requirements.txt
ERROR: Could not find a version that satisfies the requirement mmcv-full==1.7.1
ERROR: No matching distribution found for mmcv-full==1.7.1
The example fails at the dependency installation step before any code runs.

**Logs:**
pip install mmcv-full==1.7.1
Looking in indexes: https://pypi.org/simple/
ERROR: Could not find a version that satisfies the requirement mmcv-full==1.7.1
(from versions: none available under this name)
ERROR: No matching distribution found for mmcv-full==1.7.1

**Note on MooreZheng's original feedback:** When this PR was first submitted 
in June 2023, @MooreZheng correctly noted that unknown task processing belongs 
in Lifelong Learning, not SingleTaskLearning. This architectural concern 
remains unaddressed in the merged code. The custom paradigm 
`singletasklearning_acboost` represents a workaround for what should be a 
proper lifelong learning paradigm integration.

These issues are documented in full in: 
https://github.com/kubeedge/ianvs/issues/446

**Pull request merged**
