### PR TITLE
OSPP: Implementation of Heterogeneous Multi-Edge Collaborative Neural Network Inference for High Mobility Scenarios

### PR DESCRIPTION
**Pull request by wyoung1**
This PR is implementaion of https://github.com/kubeedge/ianvs/issues/100

### CODE REVIEW

**Review by MooreZheng — CHANGES_REQUESTED** [review]
There are CI issues that remain to be resolved, see https://github.com/kubeedge/ianvs/actions/runs/11074859852?pr=151

**Comment by MooreZheng** [comment]
@hsj576 might also want to take a look at this project implementation

**Review by hsj576 — APPROVED** [review]
/lgtm

**Review by MooreZheng — COMMENTED** [review]
This pull request contains 4 commits, which might make maintenance difficult, considering the number of contributors, pull requests, and their commits in KubeEdge Ianvs recently. In the final stage, @wyoung1  can squash the commits into one using [rebase techniques](https://blog.kinboy.wang/2019/04/09/Git-%E5%8E%8B%E7%BC%A9%E5%A4%9A%E4%B8%AAcommit%E4%B8%BA%E5%8D%95%E4%B8%AAcommit/).

**Comment by wyoung1** [comment]
> This pull request contains 4 commits, which might make maintenance difficult, considering the number of contributors, pull requests, and their commits in KubeEdge Ianvs recently. In the final stage, @wyoung1 can squash the commits into one using [rebase techniques](https://blog.kinboy.wang/2019/04/09/Git-%E5%8E%8B%E7%BC%A9%E5%A4%9A%E4%B8%AAcommit%E4%B8%BA%E5%8D%95%E4%B8%AAcommit/).

Thank you for your suggestion, I have squashed all submissions into one.

**Comment by yunzhe99** [comment]
lgtm

**Review by MooreZheng — APPROVED** [review]
All concerns are fixed. Well done @wyoung1

**Comment by MooreZheng** [comment]
Related issue and PR: https://github.com/kubeedge/ianvs/issues/100 https://github.com/kubeedge/ianvs/pull/115 https://github.com/kubeedge/ianvs/pull/153 https://github.com/kubeedge/ianvs/pull/148 https://github.com/kubeedge/ianvs/pull/151

**Pull request merged**
